### PR TITLE
Show ports the Bridge can connect to on localhost

### PR DESCRIPTION
**Pull request by passabilities**

### CODE REVIEW

**Comment by karel-3d** [comment]
Hi, thanks for noticing this

New bridge (v2) does not have localhost whitelisted at all, only *.trezor.io. This list is for extension and bridge v1

I should update the doc

**Comment by karel-3d** [comment]
Never mind, brain fart. Nope 5xxx and 8xxx are still whitelisted. :D  

No it is not going away.

**Comment by karel-3d** [comment]
Btw, how exactly are you integrating trezor.js to a dapp? That sounds interesting!

**Comment by passabilities** [comment]
Why am I being told to not use this on our website by @prusnak and switch to Trezor Connect then?

Yes, I work at Totle.com and I'm working on the hardware integrations atm

**Comment by prusnak** [comment]
@karel-3d Please update the documentation according to this PR, but drop the second sentence starting with 'If you want to add your url ...'. It's no longer valid.

**Comment by karel-3d** [comment]
The docs will need bigger rewrite to make it clear we don't want people to use it from a third party sites at all

**Comment by karel-3d** [comment]
I have rewritten the readme, closing this

**Pull request closed without merging**
